language: node_js
node_js:
- 6
branches:
  only:
  - master
install:
- npm install hexo-cli -g
- npm install
addons:
  ssh_known_hosts:  47.96.87.250:22
script:
- hexo generate && rsync -az -vv --delete -e 'ssh -p 22' public/ root@47.96.87.250:/home/blog
before_install:
- openssl aes-256-cbc -K $encrypted_c0a82d889265_key -iv $encrypted_c0a82d889265_iv
  -in travis.enc -out travis -d
